export const ActionTypes = {
    SET_EPISODES : "SET_EPISODES",
    SELECTED_EPISODE : "SELECTED_EPISODE",
    REMOVE_SELECTED_EPISODE : "REMOVE_SELECTED_EPISODE",
    SET_CHARACTERS: "SET_CHARACTERS",
    SELECTED_CHARACTER: "SELECTED_CHARACTER",
    SET_FAVORITES: "SET_FAVORITES",
    SHOW_FAVORITES: "SHOW_FAVORITES",
}